server:
  port: 10010
logging:
  file: common-microservice-eureka-client-10010.log
  level: 
    com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter : OFF
    com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject : OFF
    com.gargoylesoftware.htmlunit.host.html.HTMLDocument : OFF
    com.gargoylesoftware.htmlunit.html.HtmlScript : OFF
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8888/eureka/
  instance: 
    metadata-map:
      winio: false

#数据源：
spring:
  cloud:
    stream:
      bindings: 
        output:                            # 频道名称（根据具体模块来命名）
          destination: carrier-topic-01                
          binder: kafka_binder
      binders: 
        kafka_binder: 
          type: kafka 
          environment:
            spring.cloud.stream.kafka.binder.brokers: ${kafka.brokers}
            spring.cloud.stream.kafka.binder.zk-nodes: ${kafka.zknodes} 
  datasource:
    separator: ;;
    schema: classpath:/datasource/*.sql
    initialization-mode: ${datasource.initialization-mode} 
    continueOnError: true
    hikari: 
      minimum-idle: ${datasource.jdbc.minIdle}
      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
    driver-class-name: ${datasource.jdbc.driver}
    url: ${datasource.jdbc.url}
    schema-username: ${datasource.jdbc.username} 
    schema-password: ${datasource.jdbc.password}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    type: ${datasource.jdbc.type}
  jpa: 
    show-sql: false
    hibernate: 
        ddl-auto: update 
        naming: 
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl 
    properties:  
      hibernate:   
        dialect: ${datasource.hibernate.dialect}
        temp: 
          use_jdbc_metadata_defaults: false #此处是为了解决启动时报错createClob()方法未实现
  mvc: 
    static-path-pattern: /home/seluser/snapshot/** 
  resources: 
#    static-locations: file:G:\workspace\2018-4-2\strong-auth-crawler/snapshot,file:G:\workspace\2018-4-2\strong-auth-crawler\file
    static-locations: file:./snapshot          